### ISSUE TITLE
Fix problem for config trace-context with dynamic configuration

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#1033]
**Describe the bug**
When using config center services and add 

```
spring:
  cloud:
    servicecomb:
      context:
        traceContexts: x-microservice-name,x-instance-id
```

The access log may not correctly produced. 
.

**To Reproduce**
using config center services for add trace.

**Expected behavior**

**Information**

Spring Cloud Huawei version: 
Spring Cloud version(optional):
Spring Boot version(optional):
Spring version(optional): 

**Additional context**
NA
