### ISSUE TITLE
add default settings for feign connect timeout and read timeout

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#1224]
**Is your feature request related to a problem? Please describe.**
Spring Cloud changed feign configurations.  Add default settings can be a reference and avoid less problem. 

**Describe the solution you'd like**
```
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 30000
```

```
spring: 
 cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 1000
            readTimeout: 30000
```

**Describe alternatives you've considered**
In component.yml

**Additional context**
NA
