### ISSUE TITLE
微服务使用Fallback机制时，自动切换到fallback地址后，过一段时间会自动回切到原地址，而不在乎原地址的服务是否健康

### ISSUE THREAD

**Issue by meisLi** [huaweicloud/spring-cloud-huawei#1238]
**场景：**
部署三个微服务实例，consumer，provider1和provider2，其中provider1和provider2是同一个微服务的两个实例。
consumer使用fallback机制，在simple下配置了provider1的地址，在fallback配置了provider2地址。
具体样例如下：
```
spring:
  cloud:
    discovery:
      client:
        simple:
          enabled: true
          order: 0
          instances:
            core-gateway:
              - uri: "http://localhost:9092"
                instanceId: region-gateway-01

        fallback:
          enabled: true
          global:
            uri: "http://localhost:9093"
            instanceId: fallback-region-gateway-01
```
**现象：**
当下线provider1时，consumer经过少量报错后，访问切到正常的provider2。但是过一段时间后，又会自动回切到provider1上，但provider1并没有恢复，导致consumer报错，报了几次错后又自动切换到provider2。一段时间后，又回切到provider1。以此周期性反复。
