### ISSUE TITLE
是否能提供跨应用调用的功能？目前使用1.5.1-Hoxton版本

### ISSUE THREAD

**Issue by zhangchi02** [huaweicloud/spring-cloud-huawei#377]

**Comment by develpoerX** [comment]
比如？麻烦描述一下你的用户场景。

**Comment by zhangchi02** [comment]
比如分别有X1和X2两个应用，这两个应用下的所有微服务注册到同一个服务中心，其中X1应用中的微服务a想要调用X2应用中的微服务b，当前框架没有提供跨应用服务发现的功能

**Comment by zhangchi02** [comment]
比如分别有X1和X2两个应用，这两个应用下的所有微服务注册到同一个服务中心，其中X1应用中的微服务a想要调用X2应用中的微服务b，当前框架没有提供跨应用服务发现的功能

**Comment by liubao68** [comment]
重构代码的过程中，发现可能是版本的bug， 最新的master已经修改了。 需要测试下。

**Comment by liubao68** [comment]
客户端：
```
restTemplate.getForObject("http://account-app.account/account?id=" + id, String.class);
```

服务端：
```
spring:
  cloud:
    servicecomb:
      discovery:
        allowCrossApp: true
```
