### ISSUE TITLE
spring-cloud-huawei没有file-source的开发指南，其他扩展spring cloud的也是没有的

### ISSUE THREAD

**Issue by little-cui** [huaweicloud/spring-cloud-huawei#454]

**Comment by liubao68** [comment]
微服务引擎支持的配置中心有：config-center、kie。一个微服务应用，只能连接一种配置中心。

# 微服务引擎1.0

微服务引擎1.0使用config-center作为配置中心。微服务默认会读取配置中心全局配置、服务配置。全局配置指环境和微服务相同的配置；服务配置指环境、应用、微服务名称和微服务相同的配置。微服务引擎1.0只支持key-value的配置项。如果用户需要使用yaml格式的配置文件，可以使用具体SDK提供的fileSource功能。通过在配置文件中指定fileSource的key列表，SDK会将这些key对应的value全部当成yaml解析。以Spring Cloud为例，在bootstrap.yml中增加配置项：
```
spring:
  cloud:
    servicecomb:
      config:
        fileSource: file1.yaml,file2.yaml
```
并且在配置中心创建配置：
```
file1.yaml: |
  cse.example.key1: value1
  cse.example.key2: value2
file2.yaml: |
  cse.example.key3: value3
  cse.example.key4: value4
```
应用程序中会发现4个配置项：cse.example.key1=value1，cse.example.key2=value2，cse.example.key3=value3和cse.example.key4=value4。

# 微服务引擎2.0

微服务引擎2.0使用kie作为配置中心。微服务默认会读取配置中心应用配置、服务配置、自定义配置。应用配置指环境、应用和微服务相同的配置；服务配置指环境、应用、微服务名称和微服务相同的配置。微服务可以在配置文件中指定一个特定的label及label值，自定义配置指label及label值与微服务相同的配置。简单的场景，可以使用应用级配置和服务级配置。应用级配置被该应用下的所有微服务共享，是公共配置；服务级配置只对具体微服务生效，是独享配置。复杂的场景，可以通过使用customLabel和customLabelValue来定义配置。例如某些配置，是对所有应用共享的，那么就可以使用这个机制。在配置文件增加如下配置（以Spring Cloud为例）：

```
spring:
  cloud:
    servicecomb:
      config:
        kie:
          customLabel: public# 默认值是public
          customLabelValue: default # 默认值是空字符串
```

只要配置项带有public标签，并且标签值为default，这些配置项就会对该微服务生效。把配置中心当成数据库的一个表tbl_configurations，key是主键，每个label 都是属性。客户端会根据如下3个条件查询配置：

* 自定义配置

        select * from tbl_configurations where customLabel=customLabelValue & withStrict=false

* 应用级配置

        select * from tbl_configurations where app=demo_app & environment=demo_environment & withStrict=true

* 服务级配置

        select * from tbl_configurations where app=demo_app & environment=demo_environment & service=demo_service & withStrict=true

其中，withStrict为true的时候，表示有且只有条件里面指定的属性；withStrict为false的时候，表示除了条件里面的属性，允许有其他的属性。还可以给标签app指定多个应用，或者给标签service指定多个服务，这样配置项就可以对多个服务和应用生效，非常灵活。微服务引擎2.0的TEXT、XML等类型，SDK会简单的当成key-value对使用；YAML和Properties类型， SDK会解析内容，应用程序将内容作为实际的应用程序配置项。比如：

```
类型：TEXT
key: cse.examples.hello
value: World
```

应用程序会发现1个配置项: cse.examples.hello = World。

```
类型：YAML
key: cse.examples.hello
value: |
   cse:
     key1: value1
     key2: value2
```

应用程序会发现2个配置项: cse.key1 = value1和cse.key2 = value2。
