### ISSUE TITLE
[支持2020.0.x]基于ribbon的zone aware负载均衡策略实现

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#479]

**Comment by liubao68** [comment]
Hoxton版本开发指南：

Spring Cloud默认不开启AZ亲和调用。若需开启，请将spring.cloud.servicecomb.discovery.enabledZoneAware参数值设置为true。AZ亲和相关信息配置如下所示：

```
spring:
  cloud:
    servicecomb:
      discovery:
        enabledZoneAware：true #AZ亲和开关，默认为false
        datacenter:  
          name: test #数据中心名称
          region: region1 #数据中心区域
          availableZone: zone1 #数据中心可用区
```

上述配置的具体含义如下：

* spring.cloud.servicecomb.discovery.enabledZoneAware：AZ亲和开关，boolean类型，缺省值为false。
* spring.cloud.servicecomb.discovery.datacenter.name：数据中心名称，String类型。
* spring.cloud.servicecomb.discovery.datacenter.region：数据中心区域。
* spring.cloud.servicecomb.discovery.datacenter.availableZone：数据中心可用区。
