### ISSUE TITLE
Spring Cloud Gateway使用缺省service name locator的场景支持服务动态发现

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#518]
问题：
  spring cloud gateway第一次启动的时候， 需要获取全量的服务列表。 如果这个时候， 服务未注册， 那么则获取不到服务。 
  这种场景，在spring cloud gateway第一次访问这个服务的情况，会返回404. 

目前这个场景是作为一个约束，不支持。 因为注册中心不支持服务变化通知，只支持实例变更通知。

**Comment by liubao68** [comment]
这个问题适用于使用spring cloud gateway默认服务发现的场景：

```
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
```

增加一个配置项， 可以一定程度解决这个问题：

```
spring:
  cloud:
    servicecomb:
      discovery:
        enableServicePolling: true
```

这个配置启用后，会在每次心跳成功后，查询服务列表，如果列表有变化，则会触发spring cloud gateway重新更新路由。
