### ISSUE TITLE
Spring Cloud Gateway如何配置跨域

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#560]
```
spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-origin-patterns: "*"
```

加上 `DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE` 的目的，是保证如果后台返回跨域相关头的时候， gateway不新增，否则可能导致浏览器报错，服务跨域设置不生效。
