### ISSUE TITLE
灰度发布规则在跨应用调用场景存在问题

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#669]
场景：在gateway下发灰度规则。 gateway的应用名称和目标微服务应用名称不一样。 

配置：
 
   路由规则：

```
spring:
  cloud:
    gateway:
      routes:
        - id: consumer
          uri: lb://provider-app.provider  #应用名.服务名
          filters:
            - name: governance
          predicates:
            - Path=/**
```

   灰度规则：

```
servicecomb:
    routeRule:  
      provider: | #只支持服务名，不支持应用名.服务名。使用者需要保证服务名称不重复。 
        - precedence: 2 #优先级
          match:        #匹配策略
            headers:          #header匹配
              region:            
                exact: 'providerRegion'

              type:         
                exact: gray
          route: #路由规则
            - weight: 100 #权重值
              tags:
                version: 1.0.0
              
        - precedence: 1
          route:
            - weight: 20
              tags:
                version: 0.0.1
            - weight: 80
              tags:
                version: 0.0.2
```
