### ISSUE TITLE
Do not read PAAS_CSE_SC_ENDPOINT environment first hard code

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#711]
1. read these environment will help users do not care about the address when deploy in ServiceStage
2. But when users do not want read the environment, users do not have any choice.
3. The best practice is using place holder, users can choose the preferred way

```
spring:
  application:
    # 微服务名称，本示例使用固定值(可替换成自己想要的名字)，因为微服务名称会被客户端使用，不能轻易变化。
    name: basic-provider
  cloud:
    servicecomb:
      discovery:
        # 应用名称，本示例固定值（可替换成自己想要的名字），因为只有应用名称相同的微服务才能够相互发现，不能轻易变化。
        appName: basic-application
        serviceName: ${spring.application.name}
        # 注册中心地址，本示例使用ServiceStage环境变量。建议保留这种配置方式，部署的时候，不用手工修改地址。
        address: ${PAAS_CSE_SC_ENDPOINT:http://127.0.0.1:30100}
        # 微服务版本号，本示例使用ServiceStage环境变量。建议保留这种配置方式，部署的时候，不用手工修改版本号，防止契约注册失败。
        version: ${CAS_INSTANCE_VERSION:0.0.1}
      config:
        # 配置中心地址，本示例使用ServiceStage环境变量。建议保留这种配置方式，部署的时候，不用手工修改地址。
        serverAddr: ${PAAS_CSE_CC_ENDPOINT:http://127.0.0.1:30110}
        serverType: kie
```
