### ISSUE TITLE
通过浏览器调用consumer服务，consumer服务调用provider服务，只有provider端上报数据，consumer端缺少数据上报

### ISSUE THREAD

**Issue by david6969xin** [huaweicloud/spring-cloud-huawei#761]

**Comment by liubao68** [comment]
你是如何验证的？这个需要使用最新代码， 并且consumer和provider都需要开启 客户端熔断 和 服务端熔断。 

```
servicecomb:
  matchGroup:
    AllOperation: |
      matches:
        - apiPath:
            prefix: "/"
  # 服务端熔断
  circuitBreaker:
    AllOperation: |
      minimumNumberOfCalls: 5
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 20
  # 客户端熔断
  instanceIsolation:
    AllOperation: |
      minimumNumberOfCalls: 5
      slidingWindowSize: 10
      slidingWindowType: COUNT_BASED
      failureRateThreshold: 20
```

参考：https://github.com/huaweicloud/spring-cloud-huawei/wiki/dashboard
