### ISSUE TITLE
统一和基准化微服务、实例配置

### ISSUE THREAD

**Issue by liubao68** [huaweicloud/spring-cloud-huawei#802]
微服务和实例配置：

```
spring:
  cloud:
    servicecomb:
      service:
        name: order
        version: 0.0.1
        properties:
          x-test: value
          x-test2: value2
      instance:
        initialStatus: UP
        properties:
          x-test: value
          x-test2: value2
```
